// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: (x0,x1) => x0.querySelector(x1),
      _1294: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1294(f,arguments.length,x0) }),
      _1295: (x0,x1) => x0.removeChild(x1),
      _1296: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1296(f,arguments.length,x0) }),
      _1297: (x0,x1) => x0.appendChild(x1),
      _1298: () => new Map(),
      _1299: (x0,x1,x2) => x0.set(x1,x2),
      _1300: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      _1301: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1301(f,arguments.length,x0,x1) }),
      _1302: (x0,x1) => x0.call(x1),
      _1303: (x0,x1) => new ZXing.BrowserMultiFormatReader(x0,x1),
      _1305: x0 => x0.play(),
      _1306: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1306(f,arguments.length,x0) }),
      _1307: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1307(f,arguments.length,x0) }),
      _1308: (x0,x1) => x0.append(x1),
      _1309: x0 => x0.getVideoTracks(),
      _1310: x0 => x0.getSupportedConstraints(),
      _1311: x0 => ({video: x0}),
      _1312: x0 => ({facingMode: x0}),
      _1313: (x0,x1) => x0.getUserMedia(x1),
      _1316: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1317: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1318: (x0,x1) => x0.createElement(x1),
      _1319: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1321: (x0,x1) => x0.getAttribute(x1),
      _1325: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1359: x0 => x0.toArray(),
      _1360: x0 => x0.toUint8Array(),
      _1361: x0 => ({serverTimestamps: x0}),
      _1362: x0 => ({source: x0}),
      _1363: x0 => ({merge: x0}),
      _1365: x0 => new firebase_firestore.FieldPath(x0),
      _1366: (x0,x1) => new firebase_firestore.FieldPath(x0,x1),
      _1367: (x0,x1,x2) => new firebase_firestore.FieldPath(x0,x1,x2),
      _1368: (x0,x1,x2,x3) => new firebase_firestore.FieldPath(x0,x1,x2,x3),
      _1369: (x0,x1,x2,x3,x4) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4),
      _1370: (x0,x1,x2,x3,x4,x5) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5),
      _1371: (x0,x1,x2,x3,x4,x5,x6) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6),
      _1372: (x0,x1,x2,x3,x4,x5,x6,x7) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7),
      _1373: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8),
      _1374: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8,x9),
      _1375: () => globalThis.firebase_firestore.documentId(),
      _1376: (x0,x1) => new firebase_firestore.GeoPoint(x0,x1),
      _1377: x0 => globalThis.firebase_firestore.vector(x0),
      _1378: x0 => globalThis.firebase_firestore.Bytes.fromUint8Array(x0),
      _1380: (x0,x1) => globalThis.firebase_firestore.collection(x0,x1),
      _1382: (x0,x1) => globalThis.firebase_firestore.doc(x0,x1),
      _1385: x0 => x0.call(),
      _1413: x0 => globalThis.firebase_firestore.deleteDoc(x0),
      _1414: x0 => globalThis.firebase_firestore.getDoc(x0),
      _1415: x0 => globalThis.firebase_firestore.getDocFromServer(x0),
      _1416: x0 => globalThis.firebase_firestore.getDocFromCache(x0),
      _1417: (x0,x1) => ({includeMetadataChanges: x0,source: x1}),
      _1418: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1418(f,arguments.length,x0) }),
      _1419: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1419(f,arguments.length,x0) }),
      _1420: (x0,x1,x2,x3) => globalThis.firebase_firestore.onSnapshot(x0,x1,x2,x3),
      _1421: (x0,x1,x2) => globalThis.firebase_firestore.onSnapshot(x0,x1,x2),
      _1422: (x0,x1,x2) => globalThis.firebase_firestore.setDoc(x0,x1,x2),
      _1423: (x0,x1) => globalThis.firebase_firestore.setDoc(x0,x1),
      _1424: (x0,x1) => globalThis.firebase_firestore.query(x0,x1),
      _1425: x0 => globalThis.firebase_firestore.getDocs(x0),
      _1426: x0 => globalThis.firebase_firestore.getDocsFromServer(x0),
      _1427: x0 => globalThis.firebase_firestore.getDocsFromCache(x0),
      _1428: x0 => globalThis.firebase_firestore.limit(x0),
      _1429: x0 => globalThis.firebase_firestore.limitToLast(x0),
      _1430: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1430(f,arguments.length,x0) }),
      _1431: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1431(f,arguments.length,x0) }),
      _1432: (x0,x1) => globalThis.firebase_firestore.orderBy(x0,x1),
      _1434: (x0,x1,x2) => globalThis.firebase_firestore.where(x0,x1,x2),
      _1436: x0 => globalThis.firebase_firestore.doc(x0),
      _1439: (x0,x1) => x0.data(x1),
      _1443: x0 => x0.docChanges(),
      _1451: () => globalThis.firebase_firestore.serverTimestamp(),
      _1461: (x0,x1) => globalThis.firebase_firestore.getFirestore(x0,x1),
      _1463: x0 => globalThis.firebase_firestore.Timestamp.fromMillis(x0),
      _1464: (module,f) => finalizeWrapper(f, function() { return module.exports._1464(f,arguments.length) }),
      _1597: () => globalThis.firebase_firestore.or,
      _1598: () => globalThis.firebase_firestore.and,
      _1612: x0 => x0.path,
      _1615: () => globalThis.firebase_firestore.GeoPoint,
      _1616: x0 => x0.latitude,
      _1617: x0 => x0.longitude,
      _1619: () => globalThis.firebase_firestore.VectorValue,
      _1620: () => globalThis.firebase_firestore.Bytes,
      _1623: x0 => x0.type,
      _1625: x0 => x0.doc,
      _1627: x0 => x0.oldIndex,
      _1629: x0 => x0.newIndex,
      _1631: () => globalThis.firebase_firestore.DocumentReference,
      _1635: x0 => x0.path,
      _1644: x0 => x0.metadata,
      _1645: x0 => x0.ref,
      _1650: x0 => x0.docs,
      _1652: x0 => x0.metadata,
      _1657: () => globalThis.firebase_firestore.Timestamp,
      _1658: x0 => x0.seconds,
      _1659: x0 => x0.nanoseconds,
      _1695: x0 => x0.hasPendingWrites,
      _1697: x0 => x0.fromCache,
      _1704: x0 => x0.source,
      _1709: () => globalThis.firebase_firestore.startAfter,
      _1710: () => globalThis.firebase_firestore.startAt,
      _1711: () => globalThis.firebase_firestore.endBefore,
      _1712: () => globalThis.firebase_firestore.endAt,
      _1748: (x0,x1) => x0.item(x1),
      _1750: (x0,x1) => x0.initialize(x1),
      _1751: (x0,x1) => x0.initTokenClient(x1),
      _1752: (x0,x1) => x0.initCodeClient(x1),
      _1756: (x0,x1) => ({timeout: x0,limitedUseAppCheckTokens: x1}),
      _1761: x0 => x0.decode(),
      _1762: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1763: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1764: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1764(f,arguments.length,x0) }),
      _1765: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1765(f,arguments.length,x0) }),
      _1766: x0 => x0.send(),
      _1767: () => new XMLHttpRequest(),
      _1788: x0 => x0.toJSON(),
      _1789: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1789(f,arguments.length,x0) }),
      _1790: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1790(f,arguments.length,x0) }),
      _1791: (x0,x1,x2) => x0.onAuthStateChanged(x1,x2),
      _1792: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1792(f,arguments.length,x0) }),
      _1793: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1793(f,arguments.length,x0) }),
      _1794: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1794(f,arguments.length,x0) }),
      _1795: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1795(f,arguments.length,x0) }),
      _1796: (x0,x1,x2) => x0.onIdTokenChanged(x1,x2),
      _1813: (x0,x1) => globalThis.firebase_auth.signInWithPopup(x0,x1),
      _1816: (x0,x1) => globalThis.firebase_auth.connectAuthEmulator(x0,x1),
      _1831: () => new firebase_auth.GoogleAuthProvider(),
      _1832: (x0,x1) => x0.addScope(x1),
      _1833: (x0,x1) => x0.setCustomParameters(x1),
      _1839: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromResult(x0),
      _1854: x0 => globalThis.firebase_auth.getAdditionalUserInfo(x0),
      _1855: (x0,x1,x2) => ({errorMap: x0,persistence: x1,popupRedirectResolver: x2}),
      _1856: (x0,x1) => globalThis.firebase_auth.initializeAuth(x0,x1),
      _1862: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromError(x0),
      _1877: () => globalThis.firebase_auth.debugErrorMap,
      _1880: () => globalThis.firebase_auth.browserSessionPersistence,
      _1882: () => globalThis.firebase_auth.browserLocalPersistence,
      _1884: () => globalThis.firebase_auth.indexedDBLocalPersistence,
      _1887: x0 => globalThis.firebase_auth.multiFactor(x0),
      _1888: (x0,x1) => globalThis.firebase_auth.getMultiFactorResolver(x0,x1),
      _1890: x0 => x0.currentUser,
      _1904: x0 => x0.displayName,
      _1905: x0 => x0.email,
      _1906: x0 => x0.phoneNumber,
      _1907: x0 => x0.photoURL,
      _1908: x0 => x0.providerId,
      _1909: x0 => x0.uid,
      _1910: x0 => x0.emailVerified,
      _1911: x0 => x0.isAnonymous,
      _1912: x0 => x0.providerData,
      _1913: x0 => x0.refreshToken,
      _1914: x0 => x0.tenantId,
      _1915: x0 => x0.metadata,
      _1917: x0 => x0.providerId,
      _1918: x0 => x0.signInMethod,
      _1919: x0 => x0.accessToken,
      _1920: x0 => x0.idToken,
      _1921: x0 => x0.secret,
      _1933: x0 => x0.creationTime,
      _1934: x0 => x0.lastSignInTime,
      _1939: x0 => x0.code,
      _1941: x0 => x0.message,
      _1953: x0 => x0.email,
      _1954: x0 => x0.phoneNumber,
      _1955: x0 => x0.tenantId,
      _1978: x0 => x0.user,
      _1981: x0 => x0.providerId,
      _1982: x0 => x0.profile,
      _1983: x0 => x0.username,
      _1984: x0 => x0.isNewUser,
      _1987: () => globalThis.firebase_auth.browserPopupRedirectResolver,
      _1992: x0 => x0.displayName,
      _1993: x0 => x0.enrollmentTime,
      _1994: x0 => x0.factorId,
      _1995: x0 => x0.uid,
      _1997: x0 => x0.hints,
      _1998: x0 => x0.session,
      _2000: x0 => x0.phoneNumber,
      _2012: (x0,x1) => x0.getItem(x1),
      _2018: (x0,x1) => x0.removeItem(x1),
      _2019: (x0,x1,x2) => x0.setItem(x1,x2),
      _2020: () => globalThis.firebase_core.getApps(),
      _2021: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _2022: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _2023: x0 => globalThis.firebase_core.getApp(x0),
      _2024: () => globalThis.firebase_core.getApp(),
      _2025: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _2122: () => globalThis.firebase_core.SDK_VERSION,
      _2128: x0 => x0.apiKey,
      _2130: x0 => x0.authDomain,
      _2132: x0 => x0.databaseURL,
      _2134: x0 => x0.projectId,
      _2136: x0 => x0.storageBucket,
      _2138: x0 => x0.messagingSenderId,
      _2140: x0 => x0.measurementId,
      _2142: x0 => x0.appId,
      _2144: x0 => x0.name,
      _2145: x0 => x0.options,
      _2146: (x0,x1) => globalThis.firebase_functions.getFunctions(x0,x1),
      _2148: (x0,x1,x2) => globalThis.firebase_functions.httpsCallable(x0,x1,x2),
      _2157: x0 => x0.data,
      _2169: (x0,x1) => globalThis.firebase_functions.httpsCallable(x0,x1),
      _2171: (x0,x1) => x0.debug(x1),
      _2172: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2172(f,arguments.length,x0) }),
      _2173: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2173(f,arguments.length,x0,x1) }),
      _2174: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _2175: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _2176: (x0,x1) => x0.createScriptURL(x1),
      _2177: (x0,x1,x2) => x0.createScript(x1,x2),
      _2178: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2178(f,arguments.length,x0) }),
      _2180: (x0,x1) => x0.querySelector(x1),
      _2181: x0 => x0.barcodeFormat,
      _2182: x0 => x0.text,
      _2183: x0 => x0.rawBytes,
      _2184: x0 => x0.resultPoints,
      _2186: Date.now,
      _2188: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _2189: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _2190: () => new Error().stack,
      _2191: () => typeof dartUseDateNowForTicks !== "undefined",
      _2192: () => 1000 * performance.now(),
      _2193: () => Date.now(),
      _2194: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _2195: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _2196: () => new WeakMap(),
      _2197: (map, o) => map.get(o),
      _2198: (map, o, v) => map.set(o, v),
      _2199: (exn) => exn.toString(),
      _2200: (exn) => exn.stack,
      _2201: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _2202: x0 => new WeakRef(x0),
      _2203: x0 => x0.deref(),
      _2210: () => globalThis.WeakRef,
      _2213: s => JSON.stringify(s),
      _2214: s => printToConsole(s),
      _2215: (o, p, r) => o.replaceAll(p, () => r),
      _2216: (o, p, r) => o.replace(p, () => r),
      _2217: Function.prototype.call.bind(String.prototype.toLowerCase),
      _2218: s => s.toUpperCase(),
      _2219: s => s.trim(),
      _2220: s => s.trimLeft(),
      _2221: s => s.trimRight(),
      _2222: (string, times) => string.repeat(times),
      _2223: Function.prototype.call.bind(String.prototype.indexOf),
      _2224: (s, p, i) => s.lastIndexOf(p, i),
      _2225: (string, token) => string.split(token),
      _2226: Object.is,
      _2230: (o, c) => o instanceof c,
      _2231: o => Object.keys(o),
      _2261: x0 => new Array(x0),
      _2263: x0 => x0.length,
      _2265: (x0,x1) => x0[x1],
      _2266: (x0,x1,x2) => { x0[x1] = x2 },
      _2269: (x0,x1,x2) => new DataView(x0,x1,x2),
      _2271: x0 => new Int8Array(x0),
      _2272: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _2274: x0 => new Uint8ClampedArray(x0),
      _2276: x0 => new Int16Array(x0),
      _2278: x0 => new Uint16Array(x0),
      _2280: x0 => new Int32Array(x0),
      _2282: x0 => new Uint32Array(x0),
      _2284: x0 => new Float32Array(x0),
      _2286: x0 => new Float64Array(x0),
      _2309: x0 => x0.random(),
      _2310: (x0,x1) => x0.getRandomValues(x1),
      _2311: () => globalThis.crypto,
      _2312: () => globalThis.Math,
      _2325: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _2326: (handle) => clearTimeout(handle),
      _2327: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _2328: (handle) => clearInterval(handle),
      _2329: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _2330: () => Date.now(),
      _2331: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _2332: (x0,x1) => x0.exec(x1),
      _2333: (x0,x1) => x0.test(x1),
      _2334: x0 => x0.pop(),
      _2336: o => o === undefined,
      _2338: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _2340: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _2341: o => o instanceof RegExp,
      _2342: (l, r) => l === r,
      _2343: o => o,
      _2344: o => o,
      _2345: o => o,
      _2346: b => !!b,
      _2347: o => o.length,
      _2349: (o, i) => o[i],
      _2350: f => f.dartFunction,
      _2351: () => ({}),
      _2352: () => [],
      _2354: () => globalThis,
      _2355: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _2356: (o, p) => p in o,
      _2357: (o, p) => o[p],
      _2358: (o, p, v) => o[p] = v,
      _2359: (o, m, a) => o[m].apply(o, a),
      _2361: o => String(o),
      _2362: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _2363: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2363(f,arguments.length,x0) }),
      _2364: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2364(f,arguments.length,x0,x1) }),
      _2365: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _2366: o => [o],
      _2367: (o0, o1) => [o0, o1],
      _2368: (o0, o1, o2) => [o0, o1, o2],
      _2369: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _2370: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2371: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2374: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2375: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2376: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2377: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2378: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2379: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2380: x0 => new ArrayBuffer(x0),
      _2381: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _2383: x0 => x0.index,
      _2384: x0 => x0.groups,
      _2385: x0 => x0.flags,
      _2386: x0 => x0.multiline,
      _2387: x0 => x0.ignoreCase,
      _2388: x0 => x0.unicode,
      _2389: x0 => x0.dotAll,
      _2390: (x0,x1) => { x0.lastIndex = x1 },
      _2391: (o, p) => p in o,
      _2392: (o, p) => o[p],
      _2393: (o, p, v) => o[p] = v,
      _2394: (o, p) => delete o[p],
      _2402: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2402(f,arguments.length,x0) }),
      _2403: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2403(f,arguments.length,x0) }),
      _2425: x0 => x0.trustedTypes,
      _2426: (x0,x1) => { x0.src = x1 },
      _2427: (x0,x1) => x0.createScriptURL(x1),
      _2428: x0 => x0.nonce,
      _2429: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2429(f,arguments.length,x0) }),
      _2430: x0 => ({createScriptURL: x0}),
      _2431: (x0,x1) => x0.querySelectorAll(x1),
      _2432: x0 => x0.attachStreamToVideo,
      _2434: x0 => x0.decodeContinuously,
      _2438: x0 => x0.reset,
      _2440: x0 => x0.stopContinuousDecode,
      _2442: x0 => x0.stream,
      _2443: x0 => x0.videoElement,
      _2444: (x0,x1) => x0.key(x1),
      _2446: x0 => x0.facingMode,
      _2447: x0 => x0.getSettings(),
      _2448: (x0,x1) => ({width: x0,height: x1}),
      _2449: (x0,x1,x2) => ({width: x0,height: x1,facingMode: x2}),
      _2451: x0 => x0.trustedTypes,
      _2452: (x0,x1) => { x0.text = x1 },
      _2453: o => o instanceof Array,
      _2454: (a, i) => a.push(i),
      _2458: a => a.pop(),
      _2459: (a, i) => a.splice(i, 1),
      _2461: (a, s, e) => a.slice(s, e),
      _2464: a => a.length,
      _2466: (a, i) => a[i],
      _2467: (a, i, v) => a[i] = v,
      _2469: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2470: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2472: o => o instanceof Uint8Array,
      _2473: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2474: o => o instanceof Int8Array,
      _2475: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2476: o => o instanceof Uint8ClampedArray,
      _2477: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2478: o => o instanceof Uint16Array,
      _2479: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2480: o => o instanceof Int16Array,
      _2481: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2482: o => o instanceof Uint32Array,
      _2483: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2484: o => o instanceof Int32Array,
      _2485: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2487: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2488: o => o instanceof Float32Array,
      _2489: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2490: o => o instanceof Float64Array,
      _2491: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2492: (t, s) => t.set(s),
      _2493: l => new DataView(new ArrayBuffer(l)),
      _2494: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2496: o => o.buffer,
      _2497: o => o.byteOffset,
      _2498: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2499: (b, o) => new DataView(b, o),
      _2500: (b, o, l) => new DataView(b, o, l),
      _2501: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2502: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2503: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2504: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2505: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2506: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2507: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2508: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2509: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2510: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2511: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2512: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2515: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2516: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2517: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2518: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2519: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2520: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2521: Function.prototype.call.bind(Number.prototype.toString),
      _2522: Function.prototype.call.bind(BigInt.prototype.toString),
      _2523: Function.prototype.call.bind(Number.prototype.toString),
      _2524: (d, digits) => d.toFixed(digits),
      _2536: () => globalThis.document,
      _2559: (x0,x1) => { x0.src = x1 },
      _2560: x0 => x0.naturalWidth,
      _2561: x0 => x0.naturalHeight,
      _2577: x0 => x0.status,
      _2578: (x0,x1) => { x0.responseType = x1 },
      _2580: x0 => x0.response,
      _2581: x0 => x0.x,
      _2582: x0 => x0.y,
      _2583: () => globalThis.google.accounts.oauth2,
      _2588: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2588(f,arguments.length,x0) }),
      _2589: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2589(f,arguments.length,x0) }),
      _2590: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12) => ({client_id: x0,scope: x1,include_granted_scopes: x2,redirect_uri: x3,callback: x4,state: x5,enable_granular_consent: x6,enable_serial_consent: x7,login_hint: x8,hd: x9,ux_mode: x10,select_account: x11,error_callback: x12}),
      _2594: x0 => x0.error,
      _2597: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2597(f,arguments.length,x0) }),
      _2598: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2598(f,arguments.length,x0) }),
      _2599: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) => ({client_id: x0,callback: x1,scope: x2,include_granted_scopes: x3,prompt: x4,enable_granular_consent: x5,enable_serial_consent: x6,login_hint: x7,hd: x8,state: x9,error_callback: x10}),
      _2604: x0 => x0.expires_in,
      _2610: x0 => x0.error,
      _2613: x0 => x0.type,
      _2618: () => globalThis.google.accounts.id,
      _2632: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2632(f,arguments.length,x0) }),
      _2635: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16) => ({client_id: x0,auto_select: x1,callback: x2,login_uri: x3,native_callback: x4,cancel_on_tap_outside: x5,prompt_parent_id: x6,nonce: x7,context: x8,state_cookie_domain: x9,ux_mode: x10,allowed_parent_origin: x11,intermediate_iframe_close_callback: x12,itp_support: x13,login_hint: x14,hd: x15,use_fedcm_for_prompt: x16}),
      _2646: x0 => x0.error,
      _2648: x0 => x0.credential,
      _2659: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _2660: (module,f) => finalizeWrapper(f, function() { return module.exports._2660(f,arguments.length) }),
      _2757: (x0,x1) => { x0.lang = x1 },
      _2786: x0 => x0.style,
      _2845: (x0,x1) => { x0.onerror = x1 },
      _2861: (x0,x1) => { x0.onload = x1 },
      _2885: (x0,x1) => { x0.onpause = x1 },
      _2887: (x0,x1) => { x0.onplay = x1 },
      _2985: (x0,x1) => { x0.nonce = x1 },
      _3358: x0 => x0.videoWidth,
      _3359: x0 => x0.videoHeight,
      _3407: x0 => x0.paused,
      _3422: (x0,x1) => { x0.controls = x1 },
      _4021: (x0,x1) => { x0.src = x1 },
      _4023: (x0,x1) => { x0.type = x1 },
      _4027: (x0,x1) => { x0.async = x1 },
      _4029: (x0,x1) => { x0.defer = x1 },
      _4031: (x0,x1) => { x0.crossOrigin = x1 },
      _4033: (x0,x1) => { x0.text = x1 },
      _4041: (x0,x1) => { x0.charset = x1 },
      _4489: () => globalThis.window,
      _4529: x0 => x0.document,
      _4532: x0 => x0.location,
      _4551: x0 => x0.navigator,
      _4813: x0 => x0.trustedTypes,
      _4814: x0 => x0.sessionStorage,
      _4815: x0 => x0.localStorage,
      _4823: x0 => x0.href,
      _4830: x0 => x0.hostname,
      _4922: x0 => x0.mediaDevices,
      _4938: x0 => x0.userAgent,
      _5146: x0 => x0.length,
      _7097: x0 => x0.length,
      _7156: () => globalThis.document,
      _7236: x0 => x0.body,
      _7238: x0 => x0.head,
      _7565: x0 => x0.id,
      _7566: (x0,x1) => { x0.id = x1 },
      _10416: x0 => x0.label,
      _10438: x0 => x0.facingMode,
      _10652: x0 => x0.width,
      _10654: x0 => x0.height,
      _10660: x0 => x0.facingMode,
      _12179: (x0,x1) => { x0.height = x1 },
      _12373: (x0,x1) => { x0.objectFit = x1 },
      _12503: (x0,x1) => { x0.pointerEvents = x1 },
      _12801: (x0,x1) => { x0.transform = x1 },
      _12805: (x0,x1) => { x0.transformOrigin = x1 },
      _12869: (x0,x1) => { x0.width = x1 },
      _13953: () => globalThis.console,
      _13975: x0 => x0.message,
      _13981: x0 => globalThis.Wakelock.toggle(x0),
      _13983: x0 => x0.name,
      _13984: x0 => x0.message,
      _13985: x0 => x0.code,
      _13987: x0 => x0.customData,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
